create table archivos (
                          id_archivo bigint generated by default as identity,
                          url_archivo varchar(255) not null,
                          categoria varchar(255) not null,
                          fecha_subida timestamp(6) not null,
                          nombre_archivo varchar(255) not null,
                          tipo_archivo varchar(255) not null,
                          usuario_id integer not null,

                          primary key (id_archivo)
);
create table curso (
                       id_curso integer generated by default as identity,
                       curso varchar(255) not null,
                       link_certificacion varchar(255) not null,
                       usuario_id integer not null,
                       primary key (id_curso)
);
create table mensaje (
                         id_mensaje integer generated by default as identity,
                         contenido varchar(255) not null,
                         fecha timestamp(6) not null,
                         id_usuario integer not null,
                         primary key (id_mensaje)
);
create table tipo_empleado (
                               id_tipo_empleado bigint generated by default as identity,
                               nombre varchar(255) not null,
                               primary key (id_tipo_empleado)
);
create table usuario (
                         id_usuario integer generated by default as identity,
                         apellidos varchar(255) not null,
                         cuenta_bancaria varchar(255),
                         email varchar(255) not null,
                         nombre varchar(255) not null,
                         num_seguridad_social varchar(255),
                         password varchar(255) not null,
                         tipo_empleado_id bigint,
                         primary key (id_usuario)
);
CREATE TABLE fichajes (
                          id BIGSERIAL PRIMARY KEY,                -- Identificador único de cada fichaje (se genera automáticamente)
                          tipo VARCHAR(50) NOT NULL,               -- Tipo de fichaje: "Entrada" o "Salida"
                          hora VARCHAR(10) NOT NULL,               -- Hora del fichaje
                          fecha VARCHAR(30) NOT NULL,                     -- Fecha del fichaje
                          usuario_id int NOT NULL,              -- Clave foránea que referencia a la tabla usuarios
                          CONSTRAINT fk_usuario
                              FOREIGN KEY (usuario_id)             -- Relación con la tabla usuarios
                                  REFERENCES usuario(id_usuario)
                                  ON DELETE CASCADE                    -- Si un usuario es eliminado, sus fichajes también se eliminan
);

create table usuarios_vacaciones (
                                     id_usuario_vacaciones integer generated by default as identity,
                                     usuario_id integer,
                                     vacacion_id integer,
                                     primary key (id_usuario_vacaciones)
);
create table vacacion (
                          id_vacacion integer generated by default as identity,
                          aprobada boolean not null,
                          dias integer not null,
                          fecha_fin timestamp(6) not null,
                          fecha_inicio timestamp(6) not null,
                          pendiente boolean,
                          id_usuario integer not null,
                          primary key (id_vacacion)
);
alter table if exists archivos
    add constraint FKi624ubmj944vcxuqe834hucho
    foreign key (usuario_id)
    references usuario;
alter table if exists curso
    add constraint FKqgls7v9osmi479bbgi2t9aaoq
    foreign key (usuario_id)
    references usuario;
alter table if exists usuario
    add constraint FKmsql398f5cx0h4e8dg15sywof
    foreign key (tipo_empleado_id)
    references tipo_empleado;
alter table if exists usuarios_vacaciones
    add constraint FKioqsh7b13afp03g2av78oxsh
    foreign key (usuario_id)
    references usuario;
alter table if exists usuarios_vacaciones
    add constraint FKaopa27xee47eorgeijvkyuufd
    foreign key (vacacion_id)
    references vacacion;
alter table if exists vacacion
    add constraint FKiy18glww8m1xif6uni8o4a9km
    foreign key (id_usuario)
    references usuario;

-- Insertar el tipo de empleado 'Admin'


INSERT INTO tipo_empleado (id_tipo_empleado, nombre) VALUES (1, 'Admin');

-- Insertar el tipo de empleado 'Empleado'
INSERT INTO tipo_empleado (id_tipo_empleado, nombre) VALUES (2, 'Empleado');


-- Insertar un usuario con el rol de administrador
INSERT INTO usuario (
    id_usuario,
    tipo_empleado_id,
    cuenta_bancaria,
    email,
    nombre,
    num_seguridad_social,
    password,
    apellidos
) VALUES (
             1,
             1, -- Suponiendo que 1 representa 'admin'
             'ES7620770024003102575766',
             'admin@example.com',
             'Juan',
             '282-00-4266',
             'admin', -- Asegúrate de hashear las contraseñas en la práctica real
             'Pérez'
         );

-- Insertar un usuario con datos ficticios
INSERT INTO usuario (
    id_usuario,
    tipo_empleado_id,
    cuenta_bancaria,
    email,
    nombre,
    num_seguridad_social,
    password,
    apellidos
) VALUES (
             2,
             2, -- Suponiendo que 2 representa 'usuario normal'
             'ES9820385778983000760236',
             'usuario1@example.com',
             'Ana',
             '123-45-6789',
             'contraseña123',
             'Gómez'
         );

-- Insertar otro usuario con datos ficticios
INSERT INTO usuario (
    id_usuario,
    tipo_empleado_id,
    cuenta_bancaria,
    email,
    nombre,
    num_seguridad_social,
    password,
    apellidos
) VALUES (
             4,
             2,
             'ES9121000418450200051332',
             'usuario3@example.com',
             'Luis',
             '987-65-4321',
             'mipassword',
             'Martínez'
         );
INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Contrato_FrontEnd_Developer.pdf',
           '2024-10-08 21:14:56.525717',
           'contrato_trabajo_consultor_informatico.pdf',
           'application/pdf',
           'contrato',
           2
       );
INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Nomina_FrontEnd_Developer.pdf',
           '2024-10-08 21:14:56.525717',
           'nomina_front.pdf',
           'application/pdf',
           'nominas',
           2
       );

INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Nomina_FrontEnd_Developer_Nov.pdf',
           '2024-10-08 21:14:56.525717',
           'nomina_front.pdf',
         'application/pdf',
           'nominas',
           2
       );
INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Contrato_Cloud_Engineer.pdf',
           '2024-10-08 21:14:56.525717',
           'contrato_trabajo_cloud-engineer.pdf',
           'application/pdf',
           'contratos',
           4
       );
INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Nomina_Cloud_Engineer.pdf',
           '2024-10-08 21:14:56.525717',
           'nomina-cloud-engineer.pdf',
           'application/pdf',
           'nominas',
           4
       );
INSERT INTO archivos (url_archivo, fecha_subida, nombre_archivo, tipo_archivo, categoria, usuario_id)
VALUES (
           'https://bucketplanetalert.s3.amazonaws.com/Nomina_Cloud_Engineer_Nov.pdf',
           '2024-10-08 21:14:56.525717',
           'nomina-cloud-engineer.pdf',
           'application/pdf',
           'nominas',
           4
       );